### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by zgc** [happyyangyuan/springcloud-quickstart#2]
* What went wrong:
Could not resolve all files for configuration ':call-chain:zipkin-clients:zipkin-client:compileClasspath'.
> Could not resolve org.springframework.cloud:spring-cloud-starter-zipkin:1.2.5.RELEASE.
  Required by:
      project :call-chain:zipkin-clients:zipkin-client
   > Could not resolve org.springframework.cloud:spring-cloud-starter-zipkin:1.2.5.RELEASE.
      > Could not parse POM https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-starter-zipkin/1.2.5.RELEASE/spring-cloud-starter-zipkin-1.2.5.RELEASE.pom
         > Could not resolve org.springframework.cloud:spring-cloud-sleuth:1.2.5.RELEASE.
            > Could not resolve org.springframework.cloud:spring-cloud-sleuth:1.2.5.RELEASE.
               > Could not parse POM https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-sleuth/1.2.5.RELEASE/spring-cloud-sleuth-1.2.5.RELEASE.pom
                  > Unable to resolve version for dependency 'org.hamcrest:hamcrest-core:jar'
            > Could not resolve org.springframework.cloud:spring-cloud-sleuth:1.2.5.RELEASE.
               > Could not parse POM https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-sleuth/1.2.5.RELEASE/spring-cloud-sleuth-1.2.5.RELEASE.pom
                  > Unable to resolve version for dependency 'org.hamcrest:hamcrest-core:jar'
   > Could not resolve org.springframework.cloud:spring-cloud-starter-zipkin:1.2.5.RELEASE.
      > Could not parse POM https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-starter-zipkin/1.2.5.RELEASE/spring-cloud-starter-zipkin-1.2.5.RELEASE.pom
         > Could not resolve org.springframework.cloud:spring-cloud-sleuth:1.2.5.RELEASE.
            > Could not resolve org.springframework.cloud:spring-cloud-sleuth:1.2.5.RELEASE.
               > Could not parse POM https://jcenter.bintray.com/org/springframework/cloud/spring-cloud-sleuth/1.2.5.RELEASE/spring-cloud-sleuth-1.2.5.RELEASE.pom
                  > Unable to resolve version for dependency 'org.hamcrest:hamcrest-core:jar'
            > Could not resolve org.springframework.cloud:spring-cloud-sleuth:1.2.5.RELEASE.
               > Could not parse POM https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-sleuth/1.2.5.RELEASE/spring-cloud-sleuth-1.2.5.RELEASE.pom
                  > Unable to resolve version for dependency 'org.hamcrest:hamcrest-core:jar'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17m 9s
71 actionable tasks: 45 executed, 26 up-to-date

**Comment by happyyangyuan** [comment]
Use `gradle dockerBuild` instead.

**Comment by zgc** [comment]
#3
